# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Martynas G.
description: A Summary Page for Martynas Gintalas.
baseurl: ""
url: https://mgintalas.github.io/

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: martynas gintalas
  description:
    - Hi!
    - Welcome to my space.
    - A website to show you everything about me.
    - Please have a look around.
    - But do not get lost!
  #cv: cv
  navigation:
    #Experience: experience
    #Education: education
    Projects: projects
  contact:
    email: martynas.gintal@gmail.com
  profiles:
    Github: https://github.com/mgintalas
    Linkedin: https://www.linkedin.com/in/martynas-gintalas-957743b0/
    TableauPublic: https://public.tableau.com/app/profile/martynas4885/vizzes
  Repo: https://github.com/mgintalas/mgintalas.github.io

experience:
  title: Experience
  description:
    - Here is a list of my recent experiences
    - For more information please check out my Linkedin!

education:
  title: Education
  description:
    - Here are some details about my education
    - For more information please check out my Linkedin!

projects:
  title: Projects
  description:
    - Here are some of my favourite projects
    - To see more of my projects, visit my Github!

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
