title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://piazzai.github.io/hacked-jekyll

#theme: hacked-jekyll

remote_theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md