
title: Martynas Gintalas personal website
description: This is a personal website of Martynas Gintalas, Data Engineer from Lithuania
baseurl: ""
url: https://hacked-jekyll.netlify.app

#theme: hacked-jekyll

remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md