title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: "/mgintalas.github.io"
url: https://piazzai.github.io/hacked-jekyll

#theme: hacked-jekyll
remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
