source 'https://rubygems.org'

gem 'hacked-jekyll', '~> 2.0'
gem 'public_suffix'
gem 'addressable'
gem 'concurrent-ruby'
gem 'google-protobuf'
gem 'sass-embedded'
gem 'jekyll-sass-converter'
gem 'kramdown'
gem 'mercenary'
gem 'rouge'
gem 'unicode-display_width'
gem 'terminal-table'
gem 'webrick'
gem 'jekyll'